mysql

use krs028

# create tables

create table TEAM(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   MASCOT VARCHAR(50) NOT NULL,
   TOURNAMENT_SEED INT NOT NULL
);

create table PLAYER(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,

   TEAM_ID INT NOT NULL,
   FOREIGN KEY (TEAM_ID)
        REFERENCES TEAM(ID)
        ON DELETE RESTRICT
);

create table GAME(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COURT_NUM INT NOT NULL,

   HOME_TEAM_ID INT NOT NULL,
   FOREIGN KEY (HOME_TEAM_ID)
        REFERENCES TEAM(ID)
        ON DELETE RESTRICT,

   AWAY_TEAM_ID INT NOT NULL,
   FOREIGN KEY (AWAY_TEAM_ID)
        REFERENCES TEAM(ID)
        ON DELETE RESTRICT,

    DATE DATE NOT NULL

);

create table RESULT(
    GAME_ID INT NOT NULL,
    FOREIGN KEY (GAME_ID)
        REFERENCES GAME(ID)
        ON DELETE RESTRICT,

    PRIMARY KEY (GAME_ID),

    HOME_TEAM_SCORE INT NOT NULL,
    AWAY_TEAM_SCORE INT NOT NULL
);








# insert data

INSERT INTO TEAM
VALUES 
(1,'ARKANSAS','RAZORBACKS',1),
(2,'KENTUCKY','WILDCATS',2),
(3,'HARLEM','GLOBETROTTERS',3),
(4,'LSU','TIGERS',4);



INSERT INTO PLAYER
VALUES 
(1,'JD Notae','F',1),
(2,'Desi Sills','G',1),
(3,'Moses Moody','G',1),
(4,'Jalen Tate','G',1),
(5,'Justin Smith','F',1),
(6,'Jacob Toppin','F',2),
(6,'Devin Askew','G',2),
(7,'Brandon Boston Jr.','G',2),
(8,'Terrence Clarke','G',2),
(9,'Mwani Wilkinson','F',4),
(10,'Javonte Smart','G',4),
(11,'Trendon Watford','F',4);


INSERT INTO GAME
VALUES 
(1,1,1,2,STR_TO_DATE('4/25/21','%m/%d/%Y')),
(2,2,3,4,STR_TO_DATE('4/25/21','%m/%d/%Y')),
(3,1,2,4,STR_TO_DATE('4/27/21','%m/%d/%Y')),
(4,2,1,3,STR_TO_DATE('4/27/21','%m/%d/%Y'));



INSERT INTO RESULT
VALUES 
(1,86,72),
(2,77,79);





# step 1
show tables;

# step 2
describe SUPPLIER;
describe ITEM;
describe EMPLOYEE;
describe SALES;
describe INVENTORY_MGMT;


# step 3
SHOW CREATE TABLE SUPPLIER;
SHOW CREATE TABLE ITEM;
SHOW CREATE TABLE EMPLOYEE;
SHOW CREATE TABLE SALES;
SHOW CREATE TABLE INVENTORY_MGMT;


# step 4
SELECT
    COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_COLUMN_NAME IS NOT NULL AND CONSTRAINT_SCHEMA = "krs028";


# step 5
SELECT * FROM SUPPLIER;
SELECT * FROM ITEM;
SELECT * FROM EMPLOYEE;
SELECT * FROM SALES;
SELECT * FROM INVENTORY_MGMT;

# step 6
SELECT 
  SUPPLIER.NAME AS SUPPLIER_NAME,
  ITEM.NAME AS ITEM_NAME,
  ITEM.ROASTING_TYPE,
  SUPPLIER.COUNTRY
FROM INVENTORY_MGMT
INNER JOIN ITEM
INNER JOIN SUPPLIER
WHERE
    INVENTORY_MGMT.TOTAL_ITEM_SALES_3_MONTHS = (SELECT MAX(TOTAL_ITEM_SALES_3_MONTHS) FROM INVENTORY_MGMT)
    AND INVENTORY_MGMT.ITEM_ID = ITEM.ID
    AND INVENTORY_MGMT.SUPPLIER_ID = SUPPLIER.ID;


# step 7 (assuming each sale is one pound)
SELECT
    SUM(sales.PRICE_PER_LB-(sales.PRICE_PER_LB*sales.DISCOUNT*0.01)) TOTAL
FROM
    (SELECT
    ITEM.PRICE_PER_LB,
    SALES.DISCOUNT
FROM SALES
INNER JOIN ITEM
WHERE
    SALES.PURCHASE_DATE = '2021-02-12'
    AND SALES.ITEM_ID = ITEM.ID) sales;


# step 8
SELECT
    ITEM.ROASTING_TYPE,
    COUNT(ITEM.ROASTING_TYPE) COUNT
FROM ITEM
INNER JOIN SALES
WHERE
    ITEM.ID = SALES.ITEM_ID
    AND MONTH(SALES.PURCHASE_DATE) = 2
    AND ITEM.ROASTING_TYPE IS NOT NULL
GROUP BY ITEM.ROASTING_TYPE
ORDER BY COUNT DESC;

# step 9
SELECT
    EMPLOYEE.NAME EMPLOYEE,
    COUNT(EMPLOYEE.ID) COUNT
FROM ITEM
INNER JOIN EMPLOYEE
INNER JOIN SALES
WHERE
    ITEM.ID = SALES.ITEM_ID
    AND EMPLOYEE.ID = SALES.EMPLOYEE_ID
    AND ITEM.NAME = 'ALWADI'
GROUP BY EMPLOYEE.ID
ORDER BY COUNT DESC;


# step 10
SELECT
    ITEM.NAME ITEM,
    SUPPLIER.NAME SUPPLIER,
    SUPPLIER.PHONE_NUMBER
FROM 
    (
        SELECT
            ITEM_ID,
            SUPPLIER_ID
        FROM INVENTORY_MGMT
        WHERE
            TOTAL_AVAILABLE < (TOTAL_ITEM_SALES_3_MONTHS + TOTAL_AVAILABLE)*0.4
    ) IDS
INNER JOIN SUPPLIER
INNER JOIN ITEM
WHERE
    IDS.ITEM_ID = ITEM.ID
    AND IDS.SUPPLIER_ID = SUPPLIER.ID;


notee
exit

