mysql

use krs028

# create tables

create table TEAM(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   MASCOT VARCHAR(50) NOT NULL,
   TOURNAMENT_SEED INT NOT NULL
);

create table PLAYER(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    POSITION VARCHAR(50) NOT NULL,

   TEAM_ID INT NOT NULL,
   FOREIGN KEY (TEAM_ID)
        REFERENCES TEAM(ID)
        ON DELETE RESTRICT,
   
   PRICE_PER_LB DECIMAL(5,2) NOT NULL,
   ROASTING_TYPE CHAR(1)
);

create table EMPLOYEE(
   ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   OCCUPATION VARCHAR(25) NOT NULL,
   PHONE_NUMBER VARCHAR(25) NOT NULL,
   ADDRESS VARCHAR(50) NOT NULL
);

create table SALES(
   TRANS_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   
   ITEM_ID INT NOT NULL,
   FOREIGN KEY (ITEM_ID)
        REFERENCES ITEM(ID)
        ON DELETE RESTRICT,
   
   DISCOUNT INT NOT NULL,
   PURCHASE_DATE DATE NOT NULL,

   EMPLOYEE_ID INT NOT NULL,
   FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEE(ID)
        ON DELETE RESTRICT
);

create table INVENTORY_MGMT(
    ITEM_ID INT NOT NULL,
    FOREIGN KEY (ITEM_ID)
        REFERENCES ITEM(ID)
        ON DELETE RESTRICT,

    SUPPLIER_ID INT NOT NULL,
    FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIER(ID)
        ON DELETE RESTRICT,

    PRIMARY KEY (ITEM_ID, SUPPLIER_ID),
   
    TOTAL_ITEM_SALES_3_MONTHS INT NOT NULL,
    TOTAL_AVAILABLE INT NOT NULL
);

# insert data

# insert suppliers
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(1, 'KAFETOS COFFEE', 14075698878, 'GUATEMALA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(2, 'GOLDEN BEAN TRADE', 5535988761894, 'BRAZIL');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(3, 'PORT OF MOKHA', 9671234567, 'YEMEN');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(4, 'KERCHANSHE TRADING PLC', 251113716370, 'ETHIOPIA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(5, 'MERDEKA COFFEE', 622187962386, 'INDONESIA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(6, 'PREMIUM COLOMBIAN COFFEE', 5715087495, 'COLOMBIA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(7, 'KYAGALANYI COFFEE LTD', 256312265251, 'UGANDA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(8, 'MEFRAZ', 96612345678, 'SAUDI ARABIA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(9, 'RELIANCE LTD', 67512345678, 'PAPUA NEW GUINEA');
INSERT INTO SUPPLIER (ID, NAME, PHONE_NUMBER, COUNTRY) VALUES(10, 'MY ROASTING COMPANY', 14790000000, 'USA');


# insert items
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(1, 'ANTIGUA', 24.4, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(2, 'HAMBELA KIRITE', 23, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(3, 'KHAWLANI', 40, 'L');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(4, 'MOGIANA ', 25, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(5, 'ALWADI', 32, 'L');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(6, 'VOLCANICA SUPREMO', 17.99, 'D');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(7, 'PNG', 21.95, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(8, 'SUMATRA GAYO', 12.5, 'D');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(9, 'ARABICA', 19.99, 'D');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB) VALUES(10, 'GENERAL MERCHANDISE', 20);
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(11, 'SIDAMO', 23, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(12, 'GHIMBI', 20, 'M');
INSERT INTO ITEM (ID, NAME, PRICE_PER_LB, ROASTING_TYPE) VALUES(13, 'ALDURRAR', 25, 'M');


# insert employees
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(1, 'ALYSSA', 'OWNER', '479-123-4567', 'FAYETTEVILLE');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(2, 'ISAIAH', 'MANAGER', '479-456-1237', 'FAYETTEVILLE');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(3, 'JACK', 'CHIEF ROASTER', '479-000-0000', 'FAYETTEVILLE');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(4, 'EMILY', 'SALES', '479-111-1111', 'ROGERS');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(5, 'VALERIA', 'COFFEE TASTER', '479-222-2222', 'ROGERS');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(6, 'TOM', 'BARISTA', '662-333-3333', 'TUPELO');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(7, 'DANIELA', 'BARISTA', '214-000-0000', 'DALLAS');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(8, 'STEPHANIE', 'BARISTA', '479-555-5555', 'FAYETTEVILLE');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(9, 'KIARA', 'MARKETING', '479-666-6666', 'ELKINS');
INSERT INTO EMPLOYEE (ID, NAME, OCCUPATION, PHONE_NUMBER, ADDRESS) VALUES(10, 'JAMAL', 'SALES', '479-777-7777', 'FAYETTEVILLE');

# insert sales
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1001, 2, 0, '2021-2-1', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1002, 3, 10, '2021-2-5', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1003, 6, 15, '2021-2-7', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1004, 7, 0, '2021-2-12', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1005, 2, 0, '2021-2-12', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1006, 1, 10, '2021-2-12', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1007, 4, 10, '2021-2-18', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1008, 8, 20, '2021-2-20', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1009, 5, 10, '2021-2-22', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1010, 9, 20, '2021-2-25', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1011, 10, 10, '2021-2-28', 4);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1012, 1, 10, '2021-2-28', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1013, 1, 10, '2021-2-28', 10);
INSERT INTO SALES (TRANS_ID, ITEM_ID, DISCOUNT, PURCHASE_DATE, EMPLOYEE_ID) VALUES(1014, 1, 10, '2021-2-28', 4);


# insert inventory
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(1, 1, 20, 10);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(2, 4, 29, 35);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(3, 8, 33, 76);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(4, 2, 44, 19);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(5, 3, 25, 44);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(6, 6, 18, 14);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(7, 9, 34, 45);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(8, 5, 27, 36);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(9, 7, 29, 18);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(10, 10, 18, 29);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(11, 4, 52, 17);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(12, 4, 10, 49);
INSERT INTO INVENTORY_MGMT (ITEM_ID, SUPPLIER_ID, TOTAL_ITEM_SALES_3_MONTHS, TOTAL_AVAILABLE) VALUES(13, 3, 21, 33);


# step 1
show tables;

# step 2
describe SUPPLIER;
describe ITEM;
describe EMPLOYEE;
describe SALES;
describe INVENTORY_MGMT;


# step 3
SHOW CREATE TABLE SUPPLIER;
SHOW CREATE TABLE ITEM;
SHOW CREATE TABLE EMPLOYEE;
SHOW CREATE TABLE SALES;
SHOW CREATE TABLE INVENTORY_MGMT;


# step 4
SELECT
    COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_COLUMN_NAME, REFERENCED_TABLE_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_COLUMN_NAME IS NOT NULL AND CONSTRAINT_SCHEMA = "krs028";


# step 5
SELECT * FROM SUPPLIER;
SELECT * FROM ITEM;
SELECT * FROM EMPLOYEE;
SELECT * FROM SALES;
SELECT * FROM INVENTORY_MGMT;

# step 6
SELECT 
  SUPPLIER.NAME AS SUPPLIER_NAME,
  ITEM.NAME AS ITEM_NAME,
  ITEM.ROASTING_TYPE,
  SUPPLIER.COUNTRY
FROM INVENTORY_MGMT
INNER JOIN ITEM
INNER JOIN SUPPLIER
WHERE
    INVENTORY_MGMT.TOTAL_ITEM_SALES_3_MONTHS = (SELECT MAX(TOTAL_ITEM_SALES_3_MONTHS) FROM INVENTORY_MGMT)
    AND INVENTORY_MGMT.ITEM_ID = ITEM.ID
    AND INVENTORY_MGMT.SUPPLIER_ID = SUPPLIER.ID;


# step 7 (assuming each sale is one pound)
SELECT
    SUM(sales.PRICE_PER_LB-(sales.PRICE_PER_LB*sales.DISCOUNT*0.01)) TOTAL
FROM
    (SELECT
    ITEM.PRICE_PER_LB,
    SALES.DISCOUNT
FROM SALES
INNER JOIN ITEM
WHERE
    SALES.PURCHASE_DATE = '2021-02-12'
    AND SALES.ITEM_ID = ITEM.ID) sales;


# step 8
SELECT
    ITEM.ROASTING_TYPE,
    COUNT(ITEM.ROASTING_TYPE) COUNT
FROM ITEM
INNER JOIN SALES
WHERE
    ITEM.ID = SALES.ITEM_ID
    AND MONTH(SALES.PURCHASE_DATE) = 2
    AND ITEM.ROASTING_TYPE IS NOT NULL
GROUP BY ITEM.ROASTING_TYPE
ORDER BY COUNT DESC;

# step 9
SELECT
    EMPLOYEE.NAME EMPLOYEE,
    COUNT(EMPLOYEE.ID) COUNT
FROM ITEM
INNER JOIN EMPLOYEE
INNER JOIN SALES
WHERE
    ITEM.ID = SALES.ITEM_ID
    AND EMPLOYEE.ID = SALES.EMPLOYEE_ID
    AND ITEM.NAME = 'ALWADI'
GROUP BY EMPLOYEE.ID
ORDER BY COUNT DESC;


# step 10
SELECT
    ITEM.NAME ITEM,
    SUPPLIER.NAME SUPPLIER,
    SUPPLIER.PHONE_NUMBER
FROM 
    (
        SELECT
            ITEM_ID,
            SUPPLIER_ID
        FROM INVENTORY_MGMT
        WHERE
            TOTAL_AVAILABLE < (TOTAL_ITEM_SALES_3_MONTHS + TOTAL_AVAILABLE)*0.4
    ) IDS
INNER JOIN SUPPLIER
INNER JOIN ITEM
WHERE
    IDS.ITEM_ID = ITEM.ID
    AND IDS.SUPPLIER_ID = SUPPLIER.ID;


notee
exit

